apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.lab.username }}-env-manifests
  name: external-secret-pipeline
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.pipeline.ssh.keypath }}
      property: {{ .Values.pipeline.ssh.keyname }}
    secretKey: sshid
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ "{{" }} .sshid | toString {{ "}}" }}"
        id_ed2551: "{{ "{{" }} .sshid | toString {{ "}}" }}"
        id_rsa: "{{ "{{" }} .sshid | toString {{ "}}" }}"
    name: {{ .Values.pipeline.secret.name }}
