{{- if .Values.databaseSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customers.databaseSecretName" . }}
  labels:
    {{- include "customers.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUARKUS_DATASOURCE_DB_KIND: {{ .Values.databaseSecret.dbKind | default "h2" | quote }}
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.databaseSecret.jdbcUrl | default "jdbc:h2:mem:customers-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE" | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.databaseSecret.username | default "" | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.databaseSecret.password | default "" | quote }}
{{- end }}